Script started on Fri 06 Nov 2015 09:23:15 PM PST
[jflor053@hammer rshell]$ g++srshell.cpp -o rshell
[jflor053@hammer rshell]$ ./rshellll.cpp -o rshell
jflor053@hammer.cs.ucr.edu$ echo hello # echo world
hello
jflor053@hammer.cs.ucr.edu$ echo hello && echo hey && #hello
hello
hey
jflor053@hammer.cs.ucr.edu$ #echo hirld
jflor053@hammer.cs.ucr.edu$ ls -a #eecho hello && echo world
.			  LICENSE		rshell.cpp
..			  multi_command.script	single_command.script
commented_command.script  README.md
.git			  rshell
jflor053@hammer.cs.ucr.edu$ exit
[jflor053@hammer rshell]$ exit
exit

Script done on Fri 06 Nov 2015 09:24:28 PM PST
